### ISSUE TITLE
Command mode can still be entered even while in-game

### ISSUE THREAD

**Issue by chuckoy** [aapomm/running-vim#4]
Not sure if this is intended behaviour or not, but if the user accidentally types `:` while in-game, navigation controls are disabled since focus transfers to `.cmd-input`

**Comment by aapomm** [comment]
@chuckoy this is an intended behaviour. This is so that we could easily implement future in-game commands like `:pause` or `:quit` etc. Besides, this is an actual vim behaviour.

**Comment by chuckoy** [comment]
Gotcha. I'll cancel the pull request.
